-- MySQL Script generated by MySQL Workbench
-- 12/06/17 10:22:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_blog_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_user` (
  `id` VARCHAR(72) NOT NULL,
  `sex` VARCHAR(45) NULL COMMENT '性别',
  `username` VARCHAR(255) NOT NULL COMMENT '用户名',
  `email` VARCHAR(255) NULL COMMENT '邮箱',
  `password` VARCHAR(255) NOT NULL COMMENT '密码 （MD5加密）',
  `nickname` VARCHAR(255) NULL COMMENT '昵称',
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `headimgurl` VARCHAR(255) NULL COMMENT '头像地址',
  `birthday` VARCHAR(255) NULL COMMENT '生日',
  `introduce` VARCHAR(255) NULL COMMENT '自我简介',
  `addr` VARCHAR(255) NULL COMMENT '地址',
  `qq` VARCHAR(50) NULL COMMENT 'QQ\n',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_userlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_userlog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_userlog` (
  `id` VARCHAR(72) NOT NULL,
  `user_id` VARCHAR(72) NOT NULL COMMENT '用户id',
  `title` VARCHAR(255) NOT NULL COMMENT '日志标题',
  `content` TEXT NOT NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `readtimes` INT NULL COMMENT '阅读次数',
  `goodtimes` INT NULL COMMENT '点赞数',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户日志表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_userlog_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_userlog_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_userlog_comment` (
  `id` VARCHAR(72) NOT NULL,
  `blog_id` VARCHAR(72) NOT NULL COMMENT '博客id',
  `commerter_id` VARCHAR(72) NOT NULL COMMENT '评论人id（用户表id）',
  `parent_id` VARCHAR(72) NULL COMMENT '父id',
  `content` VARCHAR(255) NULL COMMENT '评论内容',
  `comment_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '评论时间',
  `reply_time` DATETIME NULL COMMENT '回复时间',
  `state` VARCHAR(6) NULL COMMENT '主人阅读状态',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`blog_id`, `commerter_id`),
  INDEX `commerterid_idx` (`commerter_id` ASC),
  CONSTRAINT `blogid`
    FOREIGN KEY (`blog_id`)
    REFERENCES `mydb`.`t_blog_userlog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commerterid`
    FOREIGN KEY (`commerter_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '日志评论表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_photo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_photo` (
  `id` VARCHAR(72) NOT NULL,
  `album_id` VARCHAR(72) NOT NULL COMMENT '相册id',
  `photourl` VARCHAR(255) NULL COMMENT '相片地址',
  `create_time` DATETIME NULL COMMENT '创建时间',
  PRIMARY KEY (`album_id`),
  INDEX `albumid_idx` (`album_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `albumid`
    FOREIGN KEY (`album_id`)
    REFERENCES `mydb`.`t_blog_album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '相片表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_album` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_album` (
  `id` VARCHAR(72) NOT NULL,
  `user_id` VARCHAR(72) NOT NULL COMMENT '用户id',
  `cover_id` VARCHAR(72) NOT NULL COMMENT '封面照片id',
  `name` VARCHAR(225) NULL COMMENT '名称',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `islocked` VARCHAR(6) NULL COMMENT '是否加密',
  `password` VARCHAR(255) NULL COMMENT '相册密码',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`user_id`, `cover_id`),
  INDEX `coverid_idx` (`cover_id` ASC),
  CONSTRAINT `coverid`
    FOREIGN KEY (`cover_id`)
    REFERENCES `mydb`.`t_blog_photo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '博客相册表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_leavemsg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_leavemsg` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_leavemsg` (
  `id` VARCHAR(72) NOT NULL,
  `user_id` VARCHAR(72) NOT NULL COMMENT '主人id',
  `leaver_id` VARCHAR(72) NOT NULL COMMENT '留言者id',
  `parent_id` VARCHAR(72) NULL COMMENT '父id',
  `content` VARCHAR(225) NULL COMMENT '内容',
  `leave_time` DATETIME NULL COMMENT '留言时间',
  `reply_time` DATETIME NULL COMMENT '回复时间',
  `state` VARCHAR(6) NULL COMMENT '阅读状态',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`user_id`, `leaver_id`),
  INDEX `leaverid_idx` (`leaver_id` ASC),
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `leaverid`
    FOREIGN KEY (`leaver_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '留言表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_friend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_friend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_friend` (
  `id` VARCHAR(72) NOT NULL,
  `user_id` VARCHAR(72) NOT NULL COMMENT '主人id',
  `friend_id` VARCHAR(72) NOT NULL COMMENT '朋友id',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`user_id`, `friend_id`),
  INDEX `friendid_idx` (`friend_id` ASC),
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `friendid`
    FOREIGN KEY (`friend_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '好友表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_signature`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_signature` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_signature` (
  `id` VARCHAR(72) NOT NULL,
  `user_id` VARCHAR(72) NOT NULL COMMENT '主人id',
  `reply_id` VARCHAR(72) NOT NULL COMMENT '回复人id',
  `parent_id` VARCHAR(72) NULL COMMENT '父id',
  `publish_time` DATETIME NULL COMMENT '发表时间',
  `reply_time` DATETIME NULL COMMENT '回复时间',
  `state` VARCHAR(6) NULL COMMENT '阅读状态',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `userid`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '个性签名表';


-- -----------------------------------------------------
-- Table `mydb`.`t_blog_photo_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_blog_photo_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_blog_photo_comment` (
  `id` VARCHAR(72) NOT NULL,
  `album_id` VARCHAR(72) NOT NULL COMMENT '相册id',
  `commenter_id` VARCHAR(72) NOT NULL COMMENT '评论者id',
  `parent_id` VARCHAR(72) NULL COMMENT '父id',
  `content` VARCHAR(255) NULL COMMENT '内容',
  `comment_time` DATETIME NULL COMMENT '评论时间',
  `reply_time` DATETIME NULL COMMENT '回复时间',
  `state` VARCHAR(6) NULL COMMENT '阅读状态',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`album_id`, `commenter_id`),
  INDEX `commenterid_idx` (`commenter_id` ASC),
  CONSTRAINT `albumid`
    FOREIGN KEY (`album_id`)
    REFERENCES `mydb`.`t_blog_album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `commenterid`
    FOREIGN KEY (`commenter_id`)
    REFERENCES `mydb`.`t_blog_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '照片评论表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
